In [12]:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)
print("Dimensions: ",end="")
print(numbers.ndim)
print(f"Shape: {numbers.shape}")

[10 20 30 40 50]
Dimensions: 1
Shape: (5,)


In [ ]:
import numpy as np
numbers=np.array([
    [10,20,30,40,50],
    [11,21,31,41,51],
    [12,22,32,42,52]
])
print(numbers)
print("Dimensions: ",end="")
print(numbers.ndim)
print(f"Shape: {numbers.shape}")


[[10 20 30 40 50]
 [11 21 31 41 51]
 [12 22 32 42 52]]
Dimensions: 2
Shape: (3, 5)
Array size: 8


In [18]:
import numpy as np
data=np.array([
    [
        [86,90],
        [98,86]
    ],
    [
        [95,83],
        [87,84]
    ]
])
print(data)
print("Dimensions: ",end="")
print(data.ndim)
print(f"Shape: {data.shape}")
print(f"Array size: {data.size}")
print(f"Data type: {data.dtype}")
arr = np.array(["AI","ML","AI","ML"])
print(arr.dtype)

[[[86 90]
  [98 86]]

 [[95 83]
  [87 84]]]
Dimensions: 3
Shape: (2, 2, 2)
Array size: 8
Data type: int64
<U2


In [27]:
# 1D Array indexing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[-4])
print(arr[2:4])
print(arr[:2])
print(arr[2:])
print(arr[2:5:2])

[10 20 30 40 50]
10
20
[30 40]
[10 20]
[30 40 50]
[30 50]


In [48]:
import numpy as np
data=np.array([
    [96,86,79],
    [70,83,85],
    [98,99,78]
])
print(data[1,1])
print(data[2,2])
print("Rows:",data[0])
print("Coloumns:",data[1:3,1:3])

83
78
Rows: [96 86 79]
Coloumns: [[83 85]
 [99 78]]


In [67]:
data = np.array([
    [22,30000,1],
    [25,45000,3],
    [30,70000,7],
    [22,30000,1],
    [25,45000,3],
    [30,70000,7],
    [28,55000,5],
    [35,90000,10]
])
salary=data[:,1]
age=data[:,0:1]
exp=data[:,:2]
print("Average Age: ",age.mean())
print("Total mothly salary paid by a company: ",salary.sum())
print("Average Salary: ",salary.mean())
print("Total Experince: ",exp.sum())
print("Average Experince: ",exp.mean())
print("Highest salary paying to an employee: ",salary.max())
print("Lowest salary paying to an employee: ",salary.min())
print("first two employees: ",*data[:2,:])
print("Salary and Experience: \n",data[:,1:])

Average Age:  27.125
Total mothly salary paid by a company:  435000
Average Salary:  54375.0
Total Experince:  435217
Average Experince:  27201.0625
Highest salary paying to an employee:  90000
Lowest salary paying to an employee:  30000
first two employees:  [   22 30000     1] [   25 45000     3]
Salary and Experience: 
 [[30000     1]
 [45000     3]
 [70000     7]
 [30000     1]
 [45000     3]
 [70000     7]
 [55000     5]
 [90000    10]]


NameError: name 'X' is not defined

[12.]
